export const TRIAL_WAREHOUSE = [
  // --- GROCERIES: DAIRY & EGGS (10) ---
  { id: 'G_01', name: 'Amul Taaza Milk 500ml', price: 28, brand: 'Amul', category: 'groceries', tags: ['dairy', 'milk'], in_stock: true },
  { id: 'G_02', name: 'Nandini GoodLife Milk 500ml', price: 30, brand: 'Nandini', category: 'groceries', tags: ['dairy', 'milk'], in_stock: true },
  { id: 'G_03', name: 'Mother Dairy Full Cream 500ml', price: 33, brand: 'MotherDairy', category: 'groceries', tags: ['dairy', 'milk'], in_stock: true },
  { id: 'G_04', name: 'Amul Salted Butter 100g', price: 58, brand: 'Amul', category: 'groceries', tags: ['dairy', 'butter'], in_stock: true },
  { id: 'G_05', name: 'Farm Fresh Eggs (6pcs)', price: 45, brand: 'FarmFresh', category: 'groceries', tags: ['protein', 'eggs'], in_stock: true },
  { id: 'G_06', name: 'Eggoz White Eggs (6pcs)', price: 52, brand: 'Eggoz', category: 'groceries', tags: ['protein', 'eggs'], in_stock: true },
  { id: 'G_07', name: 'Amul Paneer 200g', price: 90, brand: 'Amul', category: 'groceries', tags: ['dairy', 'paneer'], in_stock: true },
  { id: 'G_08', name: 'iD Fresh Curd 400g', price: 65, brand: 'iD', category: 'groceries', tags: ['dairy', 'curd'], in_stock: true },
  { id: 'G_09', name: 'Milky Mist Curd 400g', price: 60, brand: 'MilkyMist', category: 'groceries', tags: ['dairy', 'curd'], in_stock: true },
  { id: 'G_10', name: 'Britannia Cheese Slices', price: 145, brand: 'Britannia', category: 'groceries', tags: ['dairy', 'cheese'], in_stock: true },

  // --- GROCERIES: BAKERY & STAPLES (15) ---
  { id: 'G_11', name: 'Harvest Gold White Bread', price: 40, brand: 'HarvestGold', category: 'groceries', tags: ['bakery', 'bread'], in_stock: true },
  { id: 'G_12', name: 'Britannia Atta Bread', price: 45, brand: 'Britannia', category: 'groceries', tags: ['bakery', 'bread'], in_stock: true },
  { id: 'G_13', name: 'Modern Brown Bread', price: 48, brand: 'Modern', category: 'groceries', tags: ['bakery', 'bread'], in_stock: true },
  { id: 'G_14', name: 'Fortune Sunflower Oil 1L', price: 165, brand: 'Fortune', category: 'groceries', tags: ['staple', 'oil'], in_stock: true },
  { id: 'G_15', name: 'Aashirvaad Atta 5kg', price: 290, brand: 'Aashirvaad', category: 'groceries', tags: ['staple', 'atta'], in_stock: true },
  { id: 'G_16', name: 'India Gate Basmati Rice 1kg', price: 120, brand: 'IndiaGate', category: 'groceries', tags: ['staple', 'rice'], in_stock: true },
  { id: 'G_17', name: 'Tata Salt 1kg', price: 28, brand: 'Tata', category: 'groceries', tags: ['staple', 'salt'], in_stock: true },
  { id: 'G_18', name: 'Maggi Noodles (4-pack)', price: 60, brand: 'Nestle', category: 'groceries', tags: ['instant', 'noodles'], in_stock: true },
  { id: 'G_19', name: 'Yippee Noodles', price: 55, brand: 'Sunfeast', category: 'groceries', tags: ['instant', 'noodles'], in_stock: true },
  { id: 'G_20', name: 'Kelloggs Corn Flakes', price: 190, brand: 'Kelloggs', category: 'groceries', tags: ['breakfast'], in_stock: true },
  { id: 'G_21', name: 'Saffola Oats 500g', price: 110, brand: 'Saffola', category: 'groceries', tags: ['breakfast'], in_stock: true },
  { id: 'G_22', name: 'Red Label Tea 250g', price: 140, brand: 'BrookeBond', category: 'groceries', tags: ['beverage'], in_stock: true },
  { id: 'G_23', name: 'Nescafe Classic 50g', price: 165, brand: 'Nescafe', category: 'groceries', tags: ['beverage'], in_stock: true },
  { id: 'G_24', name: 'Dettol Handwash Refill', price: 99, brand: 'Dettol', category: 'groceries', tags: ['household'], in_stock: true },
  { id: 'G_25', name: 'Surf Excel Matic 1kg', price: 220, brand: 'Unilever', category: 'groceries', tags: ['household'], in_stock: true },

  // --- MEALS (15) ---
  { id: 'M_01', name: 'Chicken Biryani', price: 280, brand: 'Behrouz', category: 'meals', tags: ['indian', 'non-veg'], in_stock: true },
  { id: 'M_02', name: 'Veg Biryani', price: 220, brand: 'Paradise', category: 'meals', tags: ['indian', 'veg'], in_stock: true },
  { id: 'M_03', name: 'Margherita Pizza (Reg)', price: 199, brand: 'Dominos', category: 'meals', tags: ['italian', 'veg'], in_stock: true },
  { id: 'M_04', name: 'Peppy Paneer Pizza', price: 349, brand: 'Dominos', category: 'meals', tags: ['italian', 'veg'], in_stock: true },
  { id: 'M_05', name: 'Spicy Chicken Burger', price: 175, brand: 'McD', category: 'meals', tags: ['fastfood', 'non-veg'], in_stock: true },
  { id: 'M_06', name: 'McVeggie Burger', price: 130, brand: 'McD', category: 'meals', tags: ['fastfood', 'veg'], in_stock: true },
  { id: 'M_07', name: 'Quinoa Salad Bowl', price: 290, brand: 'EatFit', category: 'meals', tags: ['healthy', 'veg'], in_stock: true },
  { id: 'M_08', name: 'Butter Chicken + Naan', price: 320, brand: 'Empire', category: 'meals', tags: ['indian', 'non-veg'], in_stock: true },
  { id: 'M_09', name: 'Paneer Tikka Meal', price: 280, brand: 'BowlCo', category: 'meals', tags: ['indian', 'veg'], in_stock: true },
  { id: 'M_10', name: 'Hakka Noodles (Veg)', price: 180, brand: 'WowMomo', category: 'meals', tags: ['chinese', 'veg'], in_stock: true },
  { id: 'M_11', name: 'Chicken Momos (6pcs)', price: 150, brand: 'WowMomo', category: 'meals', tags: ['chinese', 'non-veg'], in_stock: true },
  { id: 'M_12', name: 'Chole Bhature (2pcs)', price: 140, brand: 'Anand', category: 'meals', tags: ['indian', 'veg'], in_stock: true },
  { id: 'M_13', name: 'Masala Dosa', price: 90, brand: 'MTR', category: 'meals', tags: ['indian', 'veg'], in_stock: true },
  { id: 'M_14', name: 'Classic Cold Coffee', price: 160, brand: 'ThirdWave', category: 'meals', tags: ['beverage'], in_stock: true },
  { id: 'M_15', name: 'Chocolate Pastry', price: 110, brand: 'Bakingo', category: 'meals', tags: ['dessert'], in_stock: true },

  // --- PHARMACY (10) ---
  { id: 'P_01', name: 'Dolo 650mg (15 tabs)', price: 32, brand: 'MicroLabs', category: 'pharmacy', tags: ['fever', 'pain'], in_stock: true },
  { id: 'P_02', name: 'Crocin Pain Relief', price: 40, brand: 'GSK', category: 'pharmacy', tags: ['fever', 'pain'], in_stock: true },
  { id: 'P_03', name: 'Vicks Vaporub 25g', price: 95, brand: 'P&G', category: 'pharmacy', tags: ['cold'], in_stock: true },
  { id: 'P_04', name: 'Digene Mint (10 tabs)', price: 25, brand: 'Abbott', category: 'pharmacy', tags: ['digestion'], in_stock: true },
  { id: 'P_05', name: 'Band-Aid (Pack of 10)', price: 45, brand: 'J&J', category: 'pharmacy', tags: ['firstaid'], in_stock: true },
  { id: 'P_06', name: 'Volini Gel 30g', price: 125, brand: 'SunPharma', category: 'pharmacy', tags: ['pain'], in_stock: true },
  { id: 'P_07', name: 'Revital H (10 caps)', price: 110, brand: 'SunPharma', category: 'pharmacy', tags: ['wellness'], in_stock: true },
  { id: 'P_08', name: 'Vitamin C 500mg', price: 60, brand: 'Limcee', category: 'pharmacy', tags: ['wellness'], in_stock: true },
  { id: 'P_09', name: 'Hand Sanitizer 100ml', price: 50, brand: 'Himalaya', category: 'pharmacy', tags: ['hygiene'], in_stock: true },
  { id: 'P_10', name: 'N95 Face Mask (1pc)', price: 80, brand: '3M', category: 'pharmacy', tags: ['hygiene'], in_stock: true },
];
